name: Hadolint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hadolint:
    name: Hadolint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
